name: lab_rat_wp_api
version: 1.1.28
description: Simple api client for wordpress and woocommerce
author: Laboratory Rat <Oleg.Timofeev20@gmail.com>
homepage: https://github.com/laboratory-rat/dart.storage
environment: 
    sdk: ">=1.8.0 <2.0.0"
dependencies:
     lr_storage: "^1.1.25"